package com.anirudh.springmediatr.core.mediatr;

/**
 * Interface for handling queries in the MediatR pattern.
 * Query handlers are responsible for processing queries and returning appropriate responses.
 *
 * @param <Q>        The type of query this handler can process.
 * @param <Response> The type of response generated by handling the query.
 * @since 1.0
 */
public interface QueryHandler<Q extends Query<Response>, Response> {

    /**
     * Handles the given query and generates a response.
     *
     * @param query The query to be processed.
     * @return The response generated after processing the query.
     */
    Response handleQuery(final Q query);
}
